from pool_models import PoolEntry


def _hair(id: str, label: str, category: str, tags: set[str] = set()) -> PoolEntry:
    return PoolEntry(id, label, {"hair", *tags}, metadata={"category": category, "label": label})


# Atomic labels transcribed from the approved Hair Reference Guide.
POOL = (
    _hair("hair_length_buzz_cut", "buzz cut", "length", {"short_hair"}),
    _hair("hair_length_very_short", "very short (pixie)", "length", {"short_hair"}),
    _hair("hair_length_short_bob", "short (bob)", "length", {"short_hair", "bob"}),
    _hair("hair_length_shoulder", "shoulder length", "length", {"shoulder_length"}),
    _hair("hair_length_medium", "medium (mid-back)", "length", {"medium_hair"}),
    _hair("hair_length_long", "long (waist length)", "length", {"long_hair"}),
    _hair("hair_length_very_long", "very long (below waist)", "length", {"long_hair"}),
    _hair("hair_texture_straight", "straight", "texture", {"straight", "sleek"}),
    _hair("hair_texture_wavy", "wavy", "texture", {"wavy", "natural"}),
    _hair("hair_texture_curly", "curly", "texture", {"curly", "natural"}),
    _hair("hair_texture_coily", "coily", "texture", {"coily", "natural"}),
    _hair("hair_texture_fine", "fine", "texture", {"fine_hair"}),
    _hair("hair_texture_thick", "thick", "texture", {"thick_hair"}),
    _hair("hair_density_fine", "fine", "density", {"fine_hair"}),
    _hair("hair_density_thick", "thick", "density", {"thick_hair"}),
    _hair("hair_colour_black", "black", "colour", {"black_hair"}),
    _hair("hair_colour_dark_brown", "dark brown", "colour", {"brown_hair"}),
    _hair("hair_colour_medium_brown", "medium brown", "colour", {"brown_hair"}),
    _hair("hair_colour_light_brown", "light brown", "colour", {"brown_hair"}),
    _hair("hair_colour_auburn", "auburn", "colour", {"auburn", "red_hair"}),
    _hair("hair_colour_red", "red", "colour", {"red_hair"}),
    _hair("hair_colour_strawberry_blonde", "strawberry blonde", "colour", {"blonde", "red_hair"}),
    _hair("hair_colour_blonde", "blonde", "colour", {"blonde"}),
    _hair("hair_colour_platinum", "platinum", "colour", {"blonde"}),
    _hair("hair_colour_grey_silver", "grey / silver", "colour", {"grey_hair"}),
    _hair("hair_colour_fantasy", "fantasy colour", "colour"),
    _hair("hair_parting_middle", "middle part", "parting", {"center_part"}),
    _hair("hair_parting_side", "side part", "parting", {"side_part"}),
    _hair("hair_fringe_none", "no bangs", "fringe", {"no_fringe"}),
    _hair("hair_fringe_side_swept", "side-swept bangs", "fringe", {"side_fringe"}),
    _hair("hair_fringe_curtain", "curtain bangs", "fringe", {"curtain_fringe"}),
    _hair("hair_fringe_straight", "straight bangs (full fringe)", "fringe", {"blunt_fringe"}),
    _hair("hair_fringe_wispy", "wispy bangs", "fringe", {"side_fringe", "messy"}),
    _hair("hair_style_straight_sleek", "straight and sleek", "style", {"sleek", "neat"}),
    _hair("hair_style_loose_waves", "loose waves", "style", {"loose", "wavy", "natural"}),
    _hair("hair_style_natural_curls", "natural curls", "style", {"loose", "curly", "natural"}),
    _hair("hair_style_messy_texture", "messy texture", "style", {"loose", "messy"}),
    _hair("hair_style_wet_look", "wet look", "style", {"sleek", "neat"}),
    _hair("hair_updo_low_bun_neat", "low bun (neat)", "style", {"tied", "updo", "neat"}),
    _hair("hair_updo_low_bun_messy", "low bun (messy)", "style", {"tied", "updo", "messy"}),
    _hair("hair_updo_high_bun", "high bun", "style", {"tied", "updo", "neat"}),
    _hair("hair_updo_ponytail_low", "ponytail (low)", "style", {"tied", "neat"}),
    _hair("hair_updo_ponytail_high", "ponytail (high)", "style", {"tied", "neat"}),
    _hair("hair_updo_braids_single", "braids (single)", "style", {"tied", "braided"}),
    _hair("hair_updo_braids_double", "braids (double)", "style", {"tied", "braided"}),
    _hair("hair_updo_half_up", "half up", "style", {"tied", "partial_updo"}),
    _hair("hair_updo_half_up_half_down", "half up / half down", "style", {"tied", "partial_updo"}),
    _hair("hair_detail_parting", "parting", "detail"),
    _hair("hair_detail_face_framing", "face-framing strands", "detail", {"face_framing"}),
    _hair("hair_detail_flyaways", "flyaways and loose hairs", "detail", {"flyaways", "messy"}),
    _hair("hair_detail_braid_texture", "braid texture", "detail", {"braided"}),
    # Named realistic examples from the guide.
    _hair("hair_example_short_bob", "short bob (sleek, modern)", "style", {"short_hair", "bob", "sleek"}),
    _hair("hair_example_wavy_shoulder", "wavy shoulder length (casual)", "style", {"wavy", "shoulder_length", "loose"}),
    _hair("hair_example_long_straight", "long straight (classic)", "style", {"long_hair", "straight", "neat"}),
    _hair("hair_example_curly_bangs", "curly with bangs (playful)", "style", {"curly", "natural"}),
    _hair("hair_example_messy_bun", "messy bun (relaxed)", "style", {"tied", "updo", "messy"}),
    _hair("hair_example_high_ponytail", "high ponytail (athletic)", "style", {"tied", "neat"}),
    _hair("hair_example_braids", "braids (youthful)", "style", {"tied", "braided"}),
    _hair("hair_colour_dyed", "dyed colour (bold)", "colour"),
    _hair("hair_auburn_natural", "natural auburn hair", "colour", {"auburn", "natural"}),
    _hair("hair_dark_brown_long", "long dark brown hair", "length", {"brown_hair", "long_hair"}),
    _hair("hair_black_bob", "collarbone-length black bob", "style", {"black_hair", "bob", "shoulder_length"}),
    _hair("hair_brown_wavy_shoulder", "medium-brown wavy shoulder-length hair", "texture", {"brown_hair", "wavy", "shoulder_length"}),
    _hair("hair_loose_updo", "messy casual updo", "style", {"natural", "messy", "updo"}),
)
